packages:
  - apps/*
  - packages/*

allowBuilds:
  better-sqlite3: true
  bufferutil: true
  es5-ext: true
  esbuild: true
  utf-8-validate: true

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
