export type SourceOperationalStatus =
  | 'SUPPORTED_VERIFIED'
  | 'SUPPORTED_DEGRADED'
  | 'CANDIDATE'
  | 'AGGREGATOR'
  | 'PROTECTED'
  | 'UNSUPPORTED'
  | 'DEAD';

export interface SourceDefinition {
  name: string;
  domain: string;
  connectorType: string;
  enabled: boolean;
  supported: boolean;
  liveVerified: boolean;
  classificationSupported: boolean;
  phoneExtractionSupported: boolean;
  discoveryMethod: 'playwright' | 'cheerio_http' | 'sitemap' | 'api' | 'none';
  ratePolicy: { minDelayMs: number; defaultMaxPages: number; maxDepth: number };
  recheckPolicy: { recheckDays: number };
  protectionPolicy: { handlesCloudflare: boolean; handlesCaptcha: boolean; cooldownMinutes: number };
  lastVerifiedAt: string;
  status: SourceOperationalStatus;
  notes?: string;
}

export const CANONICAL_SOURCE_REGISTRY: Record<string, SourceDefinition> = {
  'bina.az': {
    name: 'Bina.az',
    domain: 'bina.az',
    connectorType: 'bina_agency',
    enabled: true,
    supported: true,
    liveVerified: true,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'playwright',
    ratePolicy: { minDelayMs: 10_000, defaultMaxPages: 10, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: true, handlesCaptcha: true, cooldownMinutes: 60 },
    lastVerifiedAt: '2026-08-26T20:15:00.000Z',
    status: 'SUPPORTED_VERIFIED',
    notes: 'Dedicated Playwright connector with sitemap discovery and dynamic phone reveal',
  },
  'tap.az': {
    name: 'Tap.az',
    domain: 'tap.az',
    connectorType: 'tap_az',
    enabled: true,
    supported: true,
    liveVerified: true,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'cheerio_http',
    ratePolicy: { minDelayMs: 1_000, defaultMaxPages: 20, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T20:15:00.000Z',
    status: 'SUPPORTED_VERIFIED',
    notes: 'Dedicated Cheerio HTTP connector with seller classification and hotline exclusion',
  },
  'arenda.az': {
    name: 'Arenda.az',
    domain: 'arenda.az',
    connectorType: 'arenda_az',
    enabled: true,
    supported: true,
    liveVerified: true,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'cheerio_http',
    ratePolicy: { minDelayMs: 1_000, defaultMaxPages: 20, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T20:15:00.000Z',
    status: 'SUPPORTED_VERIFIED',
    notes: 'Dedicated Cheerio HTTP connector with seller classification and hotline exclusion',
  },
  'yeniemlak.az': {
    name: 'YeniEmlak.az',
    domain: 'yeniemlak.az',
    connectorType: 'yeniemlak_az',
    enabled: true,
    supported: true,
    liveVerified: true,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'cheerio_http',
    ratePolicy: { minDelayMs: 1_000, defaultMaxPages: 20, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T23:05:00.000Z',
    status: 'SUPPORTED_VERIFIED',
    notes: 'Dedicated Cheerio HTTP connector with seller classification and phone extraction',
  },
  'emlakbazari.az': {
    name: 'EmlakBazari.az',
    domain: 'emlakbazari.az',
    connectorType: 'emlakbazari_az',
    enabled: true,
    supported: true,
    liveVerified: true,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'cheerio_http',
    ratePolicy: { minDelayMs: 1_000, defaultMaxPages: 20, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T23:05:00.000Z',
    status: 'SUPPORTED_VERIFIED',
    notes: 'Dedicated Cheerio HTTP connector with seller classification and hotline exclusion',
  },
  'ipoteka.az': {
    name: 'Ipoteka.az',
    domain: 'ipoteka.az',
    connectorType: 'ipoteka_az',
    enabled: true,
    supported: true,
    liveVerified: true,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'cheerio_http',
    ratePolicy: { minDelayMs: 1_000, defaultMaxPages: 20, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T23:05:00.000Z',
    status: 'SUPPORTED_VERIFIED',
    notes: 'Dedicated Cheerio HTTP connector with seller classification',
  },
  'city.az': {
    name: 'City.az',
    domain: 'city.az',
    connectorType: 'city_az',
    enabled: true,
    supported: true,
    liveVerified: true,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'cheerio_http',
    ratePolicy: { minDelayMs: 1_000, defaultMaxPages: 20, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T23:05:00.000Z',
    status: 'SUPPORTED_VERIFIED',
    notes: 'Dedicated Cheerio HTTP connector with hotline exclusion',
  },
  'stop.az': {
    name: 'Stop.az',
    domain: 'stop.az',
    connectorType: 'stop_az',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'cheerio_http',
    ratePolicy: { minDelayMs: 1_000, defaultMaxPages: 10, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T20:15:00.000Z',
    status: 'DEAD',
    notes: 'Domain unreachable / host offline',
  },
  'emlak.az': {
    name: 'Emlak.az',
    domain: 'emlak.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 30 },
    lastVerifiedAt: '2026-08-26T20:15:00.000Z',
    status: 'PROTECTED',
    notes: 'Cloudflare 403 protection on direct requests',
  },
  'evler.az': {
    name: 'Evler.az',
    domain: 'evler.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 30 },
    lastVerifiedAt: '2026-08-26T20:15:00.000Z',
    status: 'PROTECTED',
    notes: 'HTTP 403 protection on direct requests',
  },
  'kub.az': {
    name: 'Kub.az',
    domain: 'kub.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T23:05:00.000Z',
    status: 'PROTECTED',
    notes: 'Cloudflare challenge protection on listing pages',
  },
  'mertebe.az': {
    name: 'Mertebe.az',
    domain: 'mertebe.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T23:05:00.000Z',
    status: 'PROTECTED',
    notes: 'Cloudflare challenge protection on listing pages',
  },
  'binalar.az': {
    name: 'Binalar.az',
    domain: 'binalar.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T20:15:00.000Z',
    status: 'AGGREGATOR',
    notes: 'Aggregator portal re-publishing listings',
  },
  'binatap.az': {
    name: 'Binatap.az',
    domain: 'binatap.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T20:15:00.000Z',
    status: 'AGGREGATOR',
    notes: 'Aggregator portal re-publishing listings',
  },
  'vipemlak.az': {
    name: 'VIPemlak.az',
    domain: 'vipemlak.az',
    connectorType: 'vipemlak_az',
    enabled: true,
    supported: true,
    liveVerified: true,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'cheerio_http',
    ratePolicy: { minDelayMs: 1_000, defaultMaxPages: 20, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-27T01:10:00.000Z',
    status: 'SUPPORTED_VERIFIED',
    notes: 'Dedicated Cheerio HTTP connector with session-preserved AJAX phone reveal',
  },
  'ev10.az': {
    name: 'Ev10.az',
    domain: 'ev10.az',
    connectorType: 'ev10_az',
    enabled: true,
    supported: true,
    liveVerified: true,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'api',
    ratePolicy: { minDelayMs: 1_000, defaultMaxPages: 20, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-27T01:15:00.000Z',
    status: 'SUPPORTED_VERIFIED',
    notes: 'Dedicated REST API connector with verified seller classification and hotline exclusion',
  },
  'lalafo.az': {
    name: 'Lalafo.az',
    domain: 'lalafo.az',
    connectorType: 'lalafo_az',
    enabled: true,
    supported: true,
    liveVerified: true,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'cheerio_http',
    ratePolicy: { minDelayMs: 1_000, defaultMaxPages: 20, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-27T01:18:00.000Z',
    status: 'SUPPORTED_VERIFIED',
    notes: 'Dedicated real estate category connector with pro/agency seller verification',
  },
  'unvan.az': {
    name: 'Unvan.az',
    domain: 'unvan.az',
    connectorType: 'unvan_az',
    enabled: true,
    supported: true,
    liveVerified: true,
    classificationSupported: true,
    phoneExtractionSupported: true,
    discoveryMethod: 'cheerio_http',
    ratePolicy: { minDelayMs: 1_000, defaultMaxPages: 20, maxDepth: 0 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-27T01:20:00.000Z',
    status: 'SUPPORTED_VERIFIED',
    notes: 'Dedicated real estate connector with AJAX phone reveal',
  },
  'ucuzemlak.az': {
    name: 'UcuzEmlak.az',
    domain: 'ucuzemlak.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T23:05:00.000Z',
    status: 'DEAD',
    notes: 'Domain offline / fetch failed',
  },
  'menzil.az': {
    name: 'Menzil.az',
    domain: 'menzil.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T23:05:00.000Z',
    status: 'DEAD',
    notes: 'Domain repurposed to website builder service',
  },
  'kupca.az': {
    name: 'Kupca.az',
    domain: 'kupca.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T23:05:00.000Z',
    status: 'DEAD',
    notes: 'Domain parking page',
  },
  'rahathome.az': {
    name: 'RahatHome.az',
    domain: 'rahathome.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T20:15:00.000Z',
    status: 'DEAD',
    notes: 'Domain offline / DNS failed',
  },
  'kiraye.az': {
    name: 'Kiraye.az',
    domain: 'kiraye.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T20:15:00.000Z',
    status: 'DEAD',
    notes: 'Domain offline / DNS failed',
  },
  'dasinmazemlak.az': {
    name: 'DasinmazEmlak.az',
    domain: 'dasinmazemlak.az',
    connectorType: 'website',
    enabled: false,
    supported: false,
    liveVerified: false,
    classificationSupported: false,
    phoneExtractionSupported: false,
    discoveryMethod: 'none',
    ratePolicy: { minDelayMs: 2_000, defaultMaxPages: 10, maxDepth: 1 },
    recheckPolicy: { recheckDays: 7 },
    protectionPolicy: { handlesCloudflare: false, handlesCaptcha: false, cooldownMinutes: 15 },
    lastVerifiedAt: '2026-08-26T20:15:00.000Z',
    status: 'DEAD',
    notes: 'SSL certificate error (HTTP 526)',
  },
};

export function extractDomainFromLocator(locator: string): string {
  const trimmed = locator.trim();
  try {
    const url = new URL(trimmed.startsWith('http') ? trimmed : `https://${trimmed}`);
    return url.hostname.toLowerCase().replace(/^www\./, '');
  } catch {
    return trimmed.toLowerCase().replace(/^www\./, '');
  }
}

export function getSourceDefinition(domainOrType: string): SourceDefinition | undefined {
  const domain = extractDomainFromLocator(domainOrType);
  if (CANONICAL_SOURCE_REGISTRY[domain]) return CANONICAL_SOURCE_REGISTRY[domain];
  for (const def of Object.values(CANONICAL_SOURCE_REGISTRY)) {
    if (def.connectorType === domainOrType) return def;
  }
  return undefined;
}

export function isSourceSupported(domainOrType: string): boolean {
  const def = getSourceDefinition(domainOrType);
  return Boolean(def?.supported);
}

export function getSourceOperationalStatus(domainOrType: string): SourceOperationalStatus {
  const def = getSourceDefinition(domainOrType);
  return def ? def.status : 'UNSUPPORTED';
}
