export const AUTO_ACCEPT_WEBSITE_THRESHOLD = 0.90;
export const WHATSAPP_REALTOR_GROUP_AUTO_ACCEPT_THRESHOLD = 0.90;
export const SOCIAL_NEW_CONTACT_AUTO_ACCEPT = false;
export const CONFIDENCE_POLICY_VERSION = '1.0.0';
export const AUTO_ACCEPT_WEBSITE_POLICY = 'AUTO_ACCEPT_WEBSITE_V1';
export const AUTO_ACCEPT_WHATSAPP_POLICY = 'AUTO_ACCEPT_WHATSAPP_V1';
