import { ApifyClient } from 'apify-client';

export class ApifyConfigurationError extends Error { override name='ApifyConfigurationError' }
export interface ApifyEnvironment { APIFY_TOKEN?:string; APIFY_MAX_RESULTS?:string; APIFY_MONTHLY_BUDGET_USD?:string; INSTAGRAM_ENABLED?:string; TIKTOK_ENABLED?:string; INSTAGRAM_ACTOR_ID?:string; TIKTOK_ACTOR_ID?:string; TIKTOK_COMMENTS_ACTOR_ID?:string; GOOGLE_MAPS_ACTOR_ID?:string }
export const ACTOR_DEFAULTS={instagram:'apify/instagram-scraper',tiktok:'clockworks/tiktok-scraper'} as const;
export function getApifyStatus(env:ApifyEnvironment){return env.APIFY_TOKEN?{configured:true,label:'Настроено'}:{configured:false,label:'Не настроено'};}

type JsonSchema={type?:string;required?:string[];properties?:Record<string,JsonSchema>;items?:JsonSchema};
export function validateActorInput(input:Record<string,unknown>,schema:JsonSchema):void{if(schema.type&&schema.type!=='object')throw new ApifyConfigurationError('Actor input schema must be an object');for(const key of schema.required??[])if(!(key in input))throw new ApifyConfigurationError(`Actor input schema requires unsupported field: ${key}`);for(const [key,value] of Object.entries(input)){const rule=schema.properties?.[key];if(!rule)throw new ApifyConfigurationError(`Actor input field is not supported by current schema: ${key}`);if(rule.type==='array'&&!Array.isArray(value))throw new ApifyConfigurationError(`Actor field ${key} must be an array`);if(rule.type==='string'&&typeof value!=='string')throw new ApifyConfigurationError(`Actor field ${key} must be a string`);if(rule.type==='integer'&&(!Number.isInteger(value)))throw new ApifyConfigurationError(`Actor field ${key} must be an integer`);}}

export function createApifyClient(env:ApifyEnvironment){if(!env.APIFY_TOKEN)throw new ApifyConfigurationError('APIFY_TOKEN is not configured');return new ApifyClient({token:env.APIFY_TOKEN});}

export function normalizeActorItem(item:Record<string,unknown>,platform:string){const text=[item.biography,item.caption,item.text,item.description,item.phone,item.phoneNumber].filter(v=>typeof v==='string').join(' ');const sourceUrl=[item.url,item.webVideoUrl,item.inputUrl].find((v):v is string=>typeof v==='string')??'';
  const locationType: 'comment' | 'post' | 'profile' = item.commentId ? 'comment' : item.caption ? 'post' : 'profile';
  return { sourceUrl, text, name: typeof item.fullName === 'string' ? item.fullName : typeof item.name === 'string' ? item.name : undefined, username: typeof item.username === 'string' ? item.username : undefined, platform, locationType };}

export async function runActorSafely(options:{actorId:string;input:Record<string,unknown>;schema:JsonSchema;env:ApifyEnvironment;estimatedItems:number;spentThisMonthUsd:number}){const maxResults=Math.max(1,Math.min(1000,Number(options.env.APIFY_MAX_RESULTS??100)));const budget=Number(options.env.APIFY_MONTHLY_BUDGET_USD??10);if(options.spentThisMonthUsd>=budget)throw new ApifyConfigurationError('Monthly Apify budget reached');if(options.estimatedItems>maxResults)throw new ApifyConfigurationError(`Estimated items exceed configured limit (${maxResults})`);validateActorInput(options.input,options.schema);const client=createApifyClient(options.env);const run=await client.actor(options.actorId).call(options.input,{maxItems:maxResults});if(!run.defaultDatasetId)return[];const {items}=await client.dataset(run.defaultDatasetId).listItems({limit:maxResults});return items;}
