import type { Classification, EvidenceInput, SourceInput } from '@ikimetr/core';
import type { CollectorDatabase } from './client.js';

const now = () => new Date().toISOString();
type RunStatus = 'queued' | 'running' | 'completed' | 'failed' | 'cancelled';

function mapSource(row: Record<string, unknown>) { return { id: row.id as number, name: row.name as string, type: row.type as SourceInput['type'], locator: row.locator as string, language: row.language as SourceInput['language'], maxPages: row.max_pages as number, maxDepth: row.max_depth as number, delayMs: row.delay_ms as number, enabled: Boolean(row.enabled), killSwitch: Boolean(row.kill_switch) }; }
function mapRun(row: Record<string, unknown>) { return { id: row.id as number, sourceId: row.source_id as number, status: row.status as RunStatus, startedAt: row.started_at as string | null, finishedAt: row.finished_at as string | null, pagesChecked: row.pages_checked as number, phonesFound: row.phones_found as number, uniquePhones: row.unique_phones as number, error: row.error as string | null, cancellationRequested: Boolean(row.cancellation_requested), needsReview: Boolean(row.needs_review) }; }
function mapContact(row: Record<string, unknown>) { return { id: row.id as number, normalizedPhone: row.normalized_phone as string, originalPhone: row.original_phone as string, isForeign: Boolean(row.is_foreign), type: row.type as string, name: row.name as string | null, agency: row.agency as string | null, username: row.username as string | null, platform: row.platform as string | null, confidence: row.confidence as number, reasons: JSON.parse(row.reasons_json as string) as string[], verificationStatus: row.verification_status as string, mergedIntoId: row.merged_into_id as number | null, firstSeenAt: row.first_seen_at as string, lastSeenAt: row.last_seen_at as string }; }

export function createRepositories(db: CollectorDatabase) {
  const audit = {
    record(action: string, entityType: string, entityId: number, details: unknown) { db.prepare('INSERT INTO audit_events(action,entity_type,entity_id,details_json,created_at) VALUES(?,?,?,?,?)').run(action, entityType, entityId, JSON.stringify(details), now()); },
    list() { return db.prepare('SELECT * FROM audit_events ORDER BY id').all() as Array<{ id: number; action: string }> },
  };
  const sources = {
    create(input: SourceInput) { const time = now(); const result = db.prepare('INSERT INTO sources(name,type,locator,language,max_pages,max_depth,delay_ms,enabled,kill_switch,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(input.name, input.type, input.locator, input.language, input.maxPages, input.maxDepth, input.delayMs, Number(input.enabled), Number(input.killSwitch), time, time); return this.get(Number(result.lastInsertRowid))!; },
    get(id: number) { const row = db.prepare('SELECT * FROM sources WHERE id=?').get(id) as Record<string, unknown> | undefined; return row ? mapSource(row) : undefined; },
    list() { return (db.prepare('SELECT * FROM sources ORDER BY id DESC').all() as Record<string, unknown>[]).map(mapSource); },
    update(id: number, input: Partial<SourceInput>) { const old = this.get(id); if (!old) throw new Error('source not found'); const next = { ...old, ...input }; db.prepare('UPDATE sources SET name=?,type=?,locator=?,language=?,max_pages=?,max_depth=?,delay_ms=?,enabled=?,kill_switch=?,updated_at=? WHERE id=?').run(next.name,next.type,next.locator,next.language,next.maxPages,next.maxDepth,next.delayMs,Number(next.enabled),Number(next.killSwitch),now(),id); return this.get(id)!; },
    remove(id: number) { return db.prepare('DELETE FROM sources WHERE id=?').run(id).changes > 0; },
  };
  const runs = {
    enqueue(sourceId: number) { try { const result = db.prepare("INSERT INTO runs(source_id,status,pages_checked,phones_found,unique_phones,cancellation_requested,needs_review,created_at) VALUES(?,'queued',0,0,0,0,0,?)").run(sourceId, now()); return this.get(Number(result.lastInsertRowid))!; } catch (error) { if (String(error).includes('UNIQUE')) throw new Error('source already has an active run'); throw error; } },
    get(id: number) { const row = db.prepare('SELECT * FROM runs WHERE id=?').get(id) as Record<string, unknown> | undefined; return row ? mapRun(row) : undefined; },
    list() { return (db.prepare('SELECT * FROM runs ORDER BY id DESC').all() as Record<string, unknown>[]).map(mapRun); },
    claimNext() { const claim = db.transaction(() => { const row = db.prepare("SELECT id FROM runs WHERE status='queued' ORDER BY id LIMIT 1").get() as {id:number}|undefined; if (!row) return undefined; db.prepare("UPDATE runs SET status='running',started_at=? WHERE id=? AND status='queued'").run(now(), row.id); return this.get(row.id); }); return claim(); },
    requestCancellation(id: number) { db.prepare('UPDATE runs SET cancellation_requested=1 WHERE id=?').run(id); },
    shouldCancel(id: number) { return Boolean((db.prepare('SELECT cancellation_requested FROM runs WHERE id=?').get(id) as {cancellation_requested:number}|undefined)?.cancellation_requested); },
    finish(id: number, status: Exclude<RunStatus, 'queued'|'running'>, counters = { pagesChecked: 0, phonesFound: 0, uniquePhones: 0 }, error?: string) { db.prepare('UPDATE runs SET status=?,finished_at=?,pages_checked=?,phones_found=?,unique_phones=?,error=? WHERE id=?').run(status,now(),counters.pagesChecked,counters.phonesFound,counters.uniquePhones,error ?? null,id); },
    recoverAbandoned() { return db.prepare("UPDATE runs SET status='failed',finished_at=?,needs_review=1,error=COALESCE(error,'Worker restarted during run') WHERE status='running'").run(now()).changes; },
  };
  const contacts = {
    persistEvidence(input: { normalizedPhone: string; isForeign: boolean; evidence: EvidenceInput; classification: Classification }) { return db.transaction(() => { const time=now(); db.prepare(`INSERT INTO contacts(normalized_phone,original_phone,is_foreign,type,name,agency,username,platform,confidence,reasons_json,rule_version,classified_at,verification_status,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(normalized_phone) DO UPDATE SET last_seen_at=excluded.last_seen_at,name=COALESCE(excluded.name,contacts.name),agency=COALESCE(excluded.agency,contacts.agency),username=COALESCE(excluded.username,contacts.username),confidence=MAX(contacts.confidence,excluded.confidence)`).run(input.normalizedPhone,input.evidence.rawPhone,Number(input.isForeign),input.classification.type,input.evidence.name ?? null,input.evidence.agency ?? null,input.evidence.username ?? null,input.evidence.platform,input.classification.confidence,JSON.stringify(input.classification.reasons),input.classification.ruleVersion,input.classification.classifiedAt,'unreviewed',time,time); const contact=this.byPhone(input.normalizedPhone)!; db.prepare('INSERT OR IGNORE INTO evidence(contact_id,source_id,source_url,location_type,excerpt,raw_phone,platform,fingerprint,discovered_at) VALUES(?,?,?,?,?,?,?,?,?)').run(contact.id,input.evidence.sourceId,input.evidence.sourceUrl,input.evidence.locationType,input.evidence.excerpt,input.evidence.rawPhone,input.evidence.platform,input.evidence.fingerprint,time); return contact; })(); },
    get(id: number) { const row=db.prepare('SELECT * FROM contacts WHERE id=?').get(id) as Record<string,unknown>|undefined; return row ? mapContact(row) : undefined; },
    byPhone(phone: string) { const row=db.prepare('SELECT * FROM contacts WHERE normalized_phone=?').get(phone) as Record<string,unknown>|undefined; return row ? mapContact(row) : undefined; },
    list(search='') { const rows = search ? db.prepare('SELECT * FROM contacts WHERE normalized_phone LIKE ? OR COALESCE(name,\'\') LIKE ? OR COALESCE(agency,\'\') LIKE ? ORDER BY id DESC').all(`%${search}%`,`%${search}%`,`%${search}%`) : db.prepare('SELECT * FROM contacts ORDER BY id DESC').all(); return (rows as Record<string,unknown>[]).map(mapContact); },
    evidenceFor(phone: string) { return db.prepare('SELECT e.* FROM evidence e JOIN contacts c ON c.id=e.contact_id WHERE c.normalized_phone=? ORDER BY e.id').all(phone) as Array<Record<string,unknown>>; },
  };
  const reviews = {
    merge(targetId:number,sourceId:number,reason:string) { return db.transaction(() => { if (targetId===sourceId) throw new Error('cannot merge a contact into itself'); const result=db.prepare('INSERT INTO contact_merges(target_contact_id,source_contact_id,reason,merged_at) VALUES(?,?,?,?)').run(targetId,sourceId,reason,now()); db.prepare('UPDATE contacts SET merged_into_id=? WHERE id=?').run(targetId,sourceId); const id=Number(result.lastInsertRowid); audit.record('contact.merge','contact',sourceId,{targetId,reason}); return {id,targetId,sourceId}; })(); },
    undoMerge(id:number,reason:string) { return db.transaction(() => { const merge=db.prepare('SELECT * FROM contact_merges WHERE id=? AND undone_at IS NULL').get(id) as {source_contact_id:number}|undefined; if(!merge) throw new Error('active merge not found'); db.prepare('UPDATE contacts SET merged_into_id=NULL WHERE id=?').run(merge.source_contact_id); db.prepare('UPDATE contact_merges SET undone_at=?,undo_reason=? WHERE id=?').run(now(),reason,id); audit.record('contact.merge.undo','contact',merge.source_contact_id,{mergeId:id,reason}); })(); },
  };
  return { sources, runs, contacts, reviews, audit };
}
